# Generated by Django 3.2.16 on 2024-05-21 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_foodgramuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptionmodel',
            constraint=models.UniqueConstraint(fields=('user', 'subscription'), name='unique_subscription'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionmodel',
            constraint=models.CheckConstraint(check=models.Q(('subscription__exact', django.db.models.expressions.F('user')), _negated=True), name='cant_follow_yourself'),
        ),
    ]
